### ISSUE TITLE
How to get "h36m_test_db.pt"?

### ISSUE THREAD

**Issue by wang-zm18** [ZhengyiLuo/MEVA#11]
The original VIBE does not use Human3.6M dataset, so could you please provide the h36m_test_db.pt file? Thank you in advance!

**Comment by wang-zm18** [comment]
Besides, how to get the augmented AMASS dataset?

**Comment by ZhengyiLuo** [comment]
Please refer to scripts/data_process/process_h36m.py and scripts/data_process/augment_amass.py
