### ISSUE TITLE
Missing files in gdown link in prepare_data.sh

### ISSUE THREAD

**Issue by LandryBulls** [ZhengyiLuo/MEVA#7]
Hello, the prepare_data.sh file was recently updated due to an expired link. However, the folder that is now downloaded does not contain the files that the remainder of the script references, specifically `model_best.pth.tar` and `yolov3.weights`. This of course causes issues when trying to use the `run_meva_on_video.py` script. 

Can you confirm that this issue or update the google drive link to a folder that contains the appropriate files?

**Comment by miaoYuanyuan** [comment]
@LandryBulls Did you solve this problem ?
