### ISSUE TITLE
Missing files drive link from prepare_data.sh

### ISSUE THREAD

**Issue by davrempe** [ZhengyiLuo/MEVA#8]
Similar to #7, when I run `prepare_data.sh` the downloaded zip file does not contain `meva_data/yolov3.weights` or `meva_data/model_best.pth.tar` which are both referenced in the script and needed to run the demo. Could you add these files to the drive link? Thanks!

**Comment by ZhengyiLuo** [comment]
My bad! I was a bit careless when updating the file. Link & zip file has been updated. Would you mind training again?

**Comment by davrempe** [comment]
Works now, thank you!
